eureka:
  instance:
    status-page-url:  http://${eureka.instance.hostname}:${server.port}/actuator/health
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    hostname: localhost
  client:
    serviceUrl:
          defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
    healthcheck:
          enabled: true