eureka:
  client:
    serviceUrl:
          defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
zuul:
  routes:
    api-a:
     path: /api-a/**
     serviceId: SERVIE-A
    api-b:
      path: /api-b/**
      serviceId: feign-consumer
  add-host-header: true
feign:
  hystrix:
    enabled: true
hystrix:
 command:
  default:
   execution:
    isolation:
      thread:
       timeoutInMilliseconds: 9000