spring:
  rabbitmq:
        host: localhost
        port: 5672
        username: springcloud
        password: 123456
zuul:
  routes:
    video-admin:
     path: /video-admin/**
    video-api:
      path: /video-api/**
  add-host-header: false
feign:
  hystrix:
    enabled: true
hystrix:
 command:
  default:
   execution:
    isolation:
      thread:
       timeoutInMilliseconds: 9000