server:
  port: 1111
eureka:
  instance:
    hostname: peer1
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/
