eureka:
  client:
    serviceUrl:
          defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pocketYY/ConfigRepo.git
          username: 304680078@qq.com
          password: lmlmd12301230