server:
  port: 1112
eureka:
  instance:
    hostname: peer2
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/