logging:
  level:
    root: info
    com.bootdo: debug
spring:
  datasource:
    info:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/zyctd-info?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
  rabbitmq:
          host: localhost
          port: 5672
          username: springcloud
          password: 123456
elasticsearch:
  cluster:
    name: my-application
  ip: 127.0.0.1
  port: 9300
  pool: 5