#服务端口配置
server:
  port: 8080
#spring cloud服务发现配置
eureka:
  client:
    serviceUrl:
          defaultZone: http\://${eureka.instance.hostname}\:${eureka.port}/eureka/
  instance:
    prefer-ip-address: true
    hostname: 192.168.6.254
  port: 8000
spring:
  #数据源配置
  datasource:
    info:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.6.254:3306/zyctd-info?useUnicode=true&characterEncoding=utf8
        username: zyctd
        password: zyctd
  #mq队列配置
  rabbitmq:
          host: localhost
          port: 5672
          username: springcloud
          password: 123456
#ES搜索配置
elasticsearch:
  cluster:
    name: my-application
    nodes: 192.168.6.254:9300
  pool: 5
#查询药材产新期
GetListCodexMonthUrl: http://www.zyctd.net/Ajax/AjaxHandle.ashx