server:
  port: 1111
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/
