server:
  port: 1112
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer2
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/
