spring:
  application:
    name: config-server
server:
  port: 7001

spring:
 cloud:
   config:
    server:
      git:
        uri: https://github.com/pocketYY/ConfigRepo
        search-paths: ConfigRepo
        default-label: master
        username: 304680078@qq.com
        password: lmlmd12301230